apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hyi24s4ug-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hyi24s4ug-java-quarkus-gitops